config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :friends
  root 'home#index'
  get 'home/about'

  namespace 'api' do
    namespace 'v1' do
      resources :friends
    end
  end

  match "404", to: "errors#not_found", via: :all
  match "500", to: "errors#internal_server_error", via: :all
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/application_controller.rb
class Api::V1::ApplicationController < ApplicationController
  # before_action :authenticate_user!          # Deviseの認証ヘルパー
  skip_forgery_protection
end

app/controllers/api/v1/friends_controller.rb
module Api 
  module V1
    class FriendsController < Api::V1::ApplicationController
      # http_basic_authenticate_with name: "admin", password: "secret"
      def index
        friends = Friend.order('created_at DESC')
        render json: {status: 'SUCCESS' , message: 'Loaded Friends' , data:friends }, status: :ok
      end

      def show
        friend = Friend.find(params[:id])
        render json: {status: 'SUCCESS' , message: 'Loaded Friend' , data:friend }, status: :ok
      end

      def create
        friend = Friend.new(friend_params)
        if friend.save
          render json: {status: 'SUCCESS' , message: 'Save Friend' , data:friend }, status: :ok
        else
          render json: {status: 'ERROR' , message: 'Friend not saved' , data:friend.errors }, status: :unprocessable_entity
        end
      end

      def destroy 
        friend = Friend.find(params[:id])
        friend.destroy
        render json: {status: 'SUCCESS' , message: 'Deleted Friend' , data:friend }, status: :ok
      end

      def update
        friend = Friend.find(params[:id])
        if friend.update_attributes(friend_params)
          render json: {status: 'SUCCESS' , message: 'Updated Friend' , data:friend }, status: :ok
        else
          render json: {status: 'ERROR' , message: 'Friend not updated' , data:friend.errors }, status: :unprocessable_entity
        end
      end

      private
      def friend_params
        params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # before_action :authenticate_user!
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
    # @friends.map do |friend|
    #   if friend.phone.length < 7
    #     friend.incomplete_flg = true
    #   end
    # end
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = Friend.new
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = Friend.new(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      puts friend_params.inspect
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      update_params = params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :incomplete_flg)
      update_params[:incomplete_flg] = true if update_params[:phone].length < 7
      update_params
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
  end
  
  def about
  end
  end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  prepend_before_action :check_captcha, only: [:create]

  private

  def check_captcha
    return if verify_recaptcha 

    self.resource = resource_class.new sign_in_params
    respond_with_navigational(resource) do
      flash.alert = "Recaptcha cannot be blank, please try again."
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for @friend do |form| %>
  <%= form.hidden_field :incomplete_flg, :value => @friend.incomplete_flg %>
  <% if @friend.errors.any? %>
    <h4 style="color:red;">Errors: </h4>
    <ul>
    <% @friend.errors.full_messages.each do |message| %>
      <li style="color:red;"><%=message%></li>
    <%end%>
    </ul>
  <% end %>

<br/>
<div>
<span><p style="color:#ff0000;">※英語・漢字は半角英数字で入力してください</p></span>
<span><input type="text" class= "form-control col-sm-12 demo" style= "width:50px;" disabled= true ></span><br>
<div>  
  <hr>
    <div class="mb-3 row form-group">
      <div class="col-sm-1">
      <label class= "fw-bold col-sm-12 col-form-label text-center" style="border-style:solid; border-color:black;color:#00008B;">必須</label>
      </div>
      <%= form.label :first_name, class: "fw-bold col-sm-2 col-form-label"%>
      <div class="col-sm-9">
        <%= form.text_field :first_name, class: "form-control col-sm-12 test-count"%>
      </div>
    </div>
    <hr>

    <div class="mb-3 row from-group">
    <div class="col-sm-1">
    <label class= "fw-bold col-sm-12 col-form-label text-center" style="border-style:solid; border-color:black;color:#00008B;">必須</label>
    </div>
      <%= form.label :last_name, class: "fw-bold col-sm-2 col-form-label" %>
      <div class="col-sm-9">
      <%= form.text_field :last_name, class: "form-control col-sm-12 test-count" %>
      </div>
    </div>
    <hr>

    <div class="mb-3 row from-group">
    <div class="col-sm-1">
      <label class= "fw-bold col-sm-12 col-form-label text-center" style="border-style:solid; border-color:black;color:#00008B;">必須</label>
    </div>
      <%= form.label :email, class: " fw-bold col-sm-2 col-form-label"%>
      <div class="col-sm-9">
      <%= form.text_field :email, class: "form-control col-sm-12 test-count" %>
      </div>
    </div>
  <hr>
    <div class="mb-3 row from-group">
    <label class= "fw-bold col-sm-1 col-form-label"></label>
      <%= form.label :phone,class: " fw-bold col-sm-2 col-form-label"%>
      <div class="col-sm-9">
      <%= form.text_field :phone, class: "form-control col-sm-12 test-count" %>
      </div>
    </div>
  <hr>
    <div class="mb-3 row from-group">
      <label class= "fw-bold col-sm-1 col-form-label"></label>
      <%= form.label :twitter, class: " fw-bold col-sm-2 col-form-label"%>
      <div class="col-sm-9">
      <%= form.text_field :twitter, class: "form-control col-sm-12 test-count" %>
      </div>
    </div>
  <hr>
  <div class="mb-3 row from-group">
      <label class= "fw-bold col-sm-1 col-form-label"></label>
      <%= form.label :checkBox, class: " fw-bold col-sm-2 col-form-label"%>
        <div class="col-sm-9 parent_checkBox">
            <%= form.check_box :checkBoxOne, class: "sub_checkBox" %>
            <%= "One" %>
            <%= form.check_box :checkBoxTwo, class: "sub_checkBox" %>
            <%= "Two" %>
            <%= form.check_box :checkBoxThree, class: "sub_checkBox" %>
            <%= "Three" %>
        </div>
    </div>
  <hr>
    <div class="mb-3 row from-group">
      <label class= "fw-bold col-sm-1 col-form-label"></label>
      <%= form.label :file, class: " fw-bold col-sm-2 col-form-label"%>
      <div class="col-sm-9 parent_file">
        <%= form.file_field :file1, class: "form-control col-sm-12 sub_file" %>
        <%= form.text_field :height, class: "form-control col-sm-12 sub_file" %>
        <%= form.text_field :weight, class: "form-control col-sm-12 sub_file" %>
      </div>
    </div>
  <hr>

</div>

  <br/>
  <div>
   <%=form.submit class: 'btn btn-custom' %>
    <%= link_to "Back to friends", friends_path, class: "btn btn-custom" %>
  </div>
<% end %>

<script>
  var friend =  <%= raw @friend.to_json %>;
  var input_count = 0, has_data, before_input_file_count;

  if (!friend.id){
    input_count = 0;
    var has_data = false;
  }else {
     var friend_elements = ["first_name", "last_name", "email", "phone", "twitter", "checkBoxOne", "checkBoxTwo", "checkBoxThree"];
    for (data of friend_elements) {
      if (friend[data]) {
        input_count++;
      }
    }
  }
  send_input_data_field_count(input_count);

  var sub_checkBoxes = document.getElementsByClassName('sub_checkBox');
  $(".sub_checkBox").on('change', function(){
    var checked_count = 0;
    for (var j = 0; j < sub_checkBoxes.length; j++){
        if (sub_checkBoxes[j].checked) {
          checked_count++;
        }
    }

    if (checked_count == 1 && this.checked) {
      input_count++;
    }else if (checked_count == 0) {
      input_count--;
    }
    send_input_data_field_count(input_count);
  });

  

  $(".sub_file").on('click', function(){
    var sub_file_count = document.querySelector(".parent_file").childNodes.length;
    console.log(sub_file_count)
    before_input_file_count = 0;
    for (var i = 0; i < sub_file_count; i++){
      if (document.querySelector(".parent_file").childNodes[i].value) {
        before_input_file_count++;
      }
    }

    if ($(this).val()) { 
      has_data = true
    }else {
      has_data = false
    }
  });

  $(".sub_file").on('change', function(){
    if ($(this).val() && before_input_file_count == 0) { 
      input_count++;
    }else if (!$(this).val() && has_data && before_input_file_count == 1) { 
      input_count--;
    }
    send_input_data_field_count(input_count);
  });

  $(".test-count").on('click', function(){
    if ($(this).val()) { 
      has_data = true
    }else {
      has_data = false
    }
  });

  $(".test-count").on('change', function(){
    if ($(this).val() && !has_data) { 
      input_count++;
    }else if (!$(this).val() && has_data) { 
      input_count--;
    }
    send_input_data_field_count(input_count);
  });

  function send_input_data_field_count(input_count){
    $.ajax({
      }).done(function (data) {
        $('.demo').val(input_count);
      });
  }

</script>

app/views/friends/edit.html.erb
<h4 class="text-center" style="color:#00008B;font-weight: bold;">検索対象データの登録修正</h4>

<%= render 'form', friend: @friend %>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="text-center" style="color:#00008B;font-weight: bold;">レポート一覧</h4>

<ul class="list-group">
  <% @friends.each do |friend| %>
    <li class="list-group-item">
<div class = " <%= friend.incomplete_flg? ? 'bg-danger' : '' %>" id = "<%= friend.id %>">
<div id = "<%= friend.id %>">
  <hr>
    <div class = "row">
      <label class="col-md-4" style="font-weight:bold;"> Name:</label>
      <div class = "col-md-8">
      <%= friend.first_name %>
      <%= friend.last_name %>
      </div>
    </div>

  <hr>
    <div class = "row">
      <label class="col-md-4" style="font-weight:bold;"> Email:</label>
      <div class = "col-md-8">
      <%= friend.email %>
      </div>
    </div>

  <hr>
    <div class = "row">
      <label class="col-md-4" style="font-weight:bold;"> Phone:</label>
      <div class = "col-md-8">
      <%= friend.phone %>
      </div>
    </div>

  <hr>
    <div class = "row">
      <label class="col-md-4" style="font-weight:bold;"> Twitter:</label>
      <div class = "col-md-8">
      <%= friend.twitter %>
      </div>
    </div>
  <br/>
    <%= link_to 'Show', friend_path(friend.id), class: "btn btn-custom"%></td>
    <%= link_to 'New', new_friend_path, class: "btn btn-custom"%></td>
    <%= link_to 'Edit', edit_friend_path(friend), class: "btn btn-custom" %>
    <%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-custom" %><br><br>
    <span id = "msg-<%= friend.id %>" class="<%= friend.incomplete_flg? ? 'incomplete-show' : 'incomplete-hide' %>">登録内容に不備があります。修正してください。</span>
  </div>
    </li>
  <%end%>
</ul>

<script>
var options =  <%= raw @friends.to_json %>;
 for(var friend of options){
  var element = document.getElementById(friend.id);
  var msg_id = "msg-"+friend.id
  var msg = document.getElementById(msg_id)
   if (friend.phone.length < 7){
    element.classList.add("bg-danger");
    msg.classList.remove("incomplete-hide");
    msg.classList.add("incomplete-show");
   }
  else{
    element.classList.remove("bg-danger");
    msg.classList.remove("incomplete-show");
    msg.classList.add("incomplete-hide");
  }
 }
</script>

app/views/friends/new.html.erb
<h4 class="text-center" style="color:#00008B;font-weight: bold;">検索対象データの登録</h4>
   <div class="container">
   <div class = "row">
    <%= render "form", friend: @friend %>
   </div>
   </div>
<br/>

app/views/friends/show.html.erb
<h4 class="text-center" style="color:#00008B;font-weight: bold;">検索対象データの詳細</h4>

<div class="container">

<hr>
  <div class = "row">
    <label class="col-md-4" style="font-weight:bold;"> Name:</label>
    <div class = "col-md-8">
    <%= @friend.first_name %>
    <%= @friend.last_name %>
    </div>
  </div>

<hr>
  <div class = "row">
    <label class="col-md-4" style="font-weight:bold;"> Email:</label>
    <div class = "col-md-8">
    <%= @friend.email %>
    </div>
  </div>

<hr>
  <div class = "row">
    <label class="col-md-4" style="font-weight:bold;"> Phone:</label>
    <div class = "col-md-8">
    <%= @friend.phone %>
    </div>
  </div>

<hr>
  <div class = "row">
    <label class="col-md-4" style="font-weight:bold;"> Twitter:</label>
    <div class = "col-md-8">
    <%= @friend.twitter %>
    </div>
  </div>
  <br/>
<%= link_to 'Back', friends_path, class: "btn btn-custom"%>
<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-custom" %>
<%= link_to 'Destroy', @friend, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-custom" %>

</div>

app/views/home/_header.html.erb
<% if user_signed_in?%>
<nav class="navbar navbar-default navbar-light bg-light" style="box-shadow: 1px 1px grey;">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= image_tag("deepx_icon_org.png", :size => "80x40") %>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>  
      </button>
    </div>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li >
          <%= link_to 'マイページ', home_about_path, class: "nav-link text-dark", style: "font-weight: bold; color: black;" %>
        </li>
        <li >
          <%= link_to '案件一覧', friends_path, class: "nav-link", style: "font-weight: bold; color: black;" %>
        </li>
        <li>
          <%= link_to '案件登録', new_friend_path, class: "nav-link", style: "font-weight: bold; color: black;" %>
        </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="dropdown" style="margin-top:10px">
            <button class="btn btn-default dropdown-toggle" style="color:#00008B; border: none; outline:none; background:none;" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              <%= icon('gear fa-1x') %> <label style="font-weight:bold;">設定</label>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
              <li><label style="line-height:25px; margin-left:15px; color:grey"><%=current_user.email%></label></li>
              <li><a href="#" style="line-height:25px; font-weight:bold;">企業一覧</a></li>
              <li><a href="#" style="line-height:25px; font-weight:bold;">企業情報変更</a></li>
              <li><a href="#" style="line-height:25px; font-weight:bold;">ユーザー一覧</a></li>
              <li><a href="#" style="line-height:25px; font-weight:bold;">ユーザー情報変更</a></li>
              <li><%= link_to 'ユーザーID変更', edit_user_registration_path, style: "line-height:25px; font-weight:bold;" %> </li>
              <li><%= link_to 'パスワード変更', edit_user_registration_path, style: "line-height:25px; font-weight:bold;" %> </li>
              <li role="separator" class="divider"></li>  
              <li><%= link_to 'ログアウト', destroy_user_session_path, style: "line-height:20px; color:#00008B; font-weight:bold;", method: :delete %></li>
            </ul>
          </div>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<%else%>
 <% new_user_registration_path%>
<%end%>

app/views/home/about.html.erb
<h3>About Us</h3>

app/views/home/index.html.erb
<h1><%= t 'home.hello' %></h1>
<%= t 'home.first_page' %>

app/views/layouts/_alert.html.erb
<div class="alert alert-danger alert-dismissible" role="alert">
  <%= alert%>
</div>

app/views/layouts/_notice.html.erb
<div class="alert alert-dismissible alert-warning" role="alert">
  <%= notice%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>(development)ページタイトル</title>
    <%= favicon_link_tag '/favicon.ico' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag 'application'%>
    <%= stylesheet_link_tag  'application', media: 'all'%>
    <script src="https://www.google.com/recaptcha/api.js?hl=ja"></script>
  </head>
  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice.present? %>
        <%= render 'layouts/notice' %>
      <%end%>
      <% if alert.present? %>
        <%= render 'layouts/alert' %>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>